# Nixpacks configuration for OneButtonPrompt
# This configuration is for Coolify deployment

[phases.setup]
nixPkgs = ["python310", "nodejs-18_x", "nginx"]

[phases.install]
cmds = [
    "python -m pip install --upgrade pip",
    "python -m pip install -r requirements.txt",
    "cd frontend && npm install"
]

[phases.build]
cmds = [
    "cd frontend && npm run build"
]

[start]
cmd = "python simple_server.py"

[variables]
PORT = "5000"
MULTI_MODEL_SUPPORT = "true"